name: gsheets
description:
  A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.4.2
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  firebase_database: ^10.0.4
  firebase_core: ^2.1.1
  googleapis: ^8.0.0
  googleapis_auth: ^1.3.0
  http:
  html:
  beautiful_soup_dart:
  meta: ^1.3.0
  collection: ^1.15.0
  openapi_dart_common: ^4.1.1
  connector_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: sdk/http/dart/connector
  core_openapi:
    git:
      url: git@github.com:open-runtime/generated_runtime.git
      path: sdk/http/dart/core
  #      url: git@bitbucket.org:pi3c3s/isomorphic_openapi.git
  #      path: ./core/dart/
  string_stats: ^0.1.0
  runtime_client:
    git:
      url: git@github.com:open-runtime/runtime_client.git
  dropdown_search: ^5.0.3
  loader_overlay: ^2.1.0
  badges: ^2.0.3
dev_dependencies:
  pedantic: ^1.11.1
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  pie_chart: ^5.3.2

  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf
          -images/piecesLogo.png

    assets:
      -assets/piecesLogo.png
      -assets/dart.jpg